version: "3.3"

services:
  master:
    image: jmeter
    tty: true
    networks: 
      - distributed
    volumes:
      - ./test:/test
    environment:
      - MODE=master
      - TEST_NAME=$TEST_NAME
      - REMOTES=$JMETER_WORKERS
    depends_on:
      - slave
    links:
      - slave

  slave:
    image: jmeter
    tty: true
    networks:
      - distributed
    environment:
      - MODE=node
      - SERVER_HOSTNAME=master
    deploy:
      replicas: 1


networks:
  distributed:
    driver: overlay