version: "3.3"
services:
  master:
    image: mtenrero/jmeter
    tty: true
    networks: 
      - distributed
    volumes:
      - ./test:/test
    environment:
      - MODE=master
      - TEST_NAME=$TEST_NAME
      - REMOTES=slave
    expose:
      - 6666
    depends_on:
      - slave
    links:
      - slave
  slave:
    image: mtenrero/jmeter
    tty: true
    networks:
      - distributed
    environment:
      - MODE=node
    expose:
      - 7777
      - 1099
      - 4445
    deploy:
      replicas: 3
  
# Only one for the whole cluster
consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  container_name: 'consul'
  environment:
    SERVICE_53_IGNORE: 'yes'
    SERVICE_8300_IGNORE: 'yes'
    SERVICE_8301_IGNORE: 'yes'
    SERVICE_8302_IGNORE: 'yes'
    SERVICE_8400_IGNORE: 'yes'
    SERVICE_8500_NAME: 'consul-admin_infra'

# Exactly one per physical node
registrator:
  command: "-internal consul://consul:8500"
  image: gliderlabs/registrator:latest
  container_name: 'registrator'
  links:
    - "consul"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

networks:
  distributed:
    driver: overlay